title: <p align="center"> Shashank Bhardwaj </p>
logo: /assets/img/profile_pic1.png

description:
  <p align="center">
  <a href="assets/Shashank_Bhardwaj-VCM.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shashankbhardwaj/">LinkedIn</a> |
  <a href="https://github.com/shanksmu">GitHub</a>
  
  <br>   
  I am a Senior Leader @ Akamai workgin in Cyber Security & Web Performance domain.
  Check out my Resume for more information.
  <br>
  </p>

theme: jekyll-theme-minimal
